### ISSUE TITLE
Running errcheck recursively (i.e. errcheck ./...)

### ISSUE THREAD

**Issue by microamp** [dominikh/go-errcheck.el#3]
Hello,

Is there any option for running `errcheck` recursively (i.e. `errcheck ./...`)? As I often want to run `errcheck` at the project root. 

Thanks!

**Comment by dominikh** [comment]
Update to version 1.1.1 (or the master branch) and you can use `go-errcheck-pkg`, which will interactively ask you for the package. This allows you to specify `./...`, which will be interpreted relative to the buffer's directory.

You could also define your own function that calls `(go-errcheck-pkg "./..." nil nil nil)`, or a function that calculates the project root if you want to use it from subdirectories.

**Comment by microamp** [comment]
Upgrade done and I managed to get it working with projectile. Thanks!
